### ISSUE TITLE
BRANCH GESTURE FONSTIONNE PAS et JE N'AI PASVOS NOMS

### ISSUE THREAD

**Issue by bobantoine** [UBowt571/TP1note8INF865#2]
BRANCH GESTURE FONSTIONNE PAS et JE N'AI PASVOS NOMS

**Comment by maskym** [comment]
problème corrigé, petit soucis lors du merge (nous débutons sur Git ...)

l'équipe : Thomas Gabriel (GABT) @thomsgab , Anatole Martin (MARA) @natoles  et Maxime Defrances (DEFM) @UBowt571 .
